#!name=SubHub
#!desc=由 SubHub 生成的 Surge 配置
[General]
loglevel = notify
dns-server = 223.5.5.5, 119.29.29.29
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
exclude-simple-hostnames = true
ipv6 = false
test-timeout = 5
internet-test-url = http://www.gstatic.com/generate_204

[Proxy]
{{proxies}}

[Proxy Group]
🚀 节点选择 = select, ♻️ 自动选择, 🎯 全球直连, {{names}}
♻️ 自动选择 = url-test, {{names}}, url = http://www.gstatic.com/generate_204, interval = 300, tolerance = 50
🎯 全球直连 = select, DIRECT

[Rule]
GEOIP,CN,DIRECT
FINAL,🚀 节点选择,dns-failed
